[project]
name = "translate-api"
version = "0.1.0"
description = "Airgaped translations"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "fastapi[standard]==0.128.2",
]

[dependency-groups]
dev = [
    "ruff==0.15.0",
]
